### ISSUE TITLE
As a User I want to be able to query data sources

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnindex#49]
We supply data source ids in our queries. For users to be able to use them effectively they need to know
which data source IDs to choose. For that they need to be able to get a list of all data sources in one query
and also supply data source IDs and get back description of the data sources.

**Comment by alexander-myltsev** [comment]
Would be fixed by https://github.com/GlobalNamesArchitecture/gnindex/issues/49
