### ISSUE TITLE
As a user I want to see in English what kind of match type I am getting for each result. I also want the match type phrase to be color-coded.

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnindex#64]
It is important to know what kind of match happened when we show results in GUI. The match type also needs to be 'translated' to proper English when it is shows at the GUI, as it is directed towards humands, and not computers. The match type phrase also needs to be color coded so people can see easily the quality of the match. The match types names are human-friendly, we just need to put spaces
to separate words. I would make them easily visible and always at the same place. Color-coded to further ease the quality estimate. For fuzzy matches we do need to show edit distances as well, probably in the same colors.

**Green**

ExactMatch

ExactCanonicalMatch

**Lighter Green**

ExactPartialMatch

**Yellow**

FuzzyCanonicalMatch

FuzzyPartialMatch

**Red (I guess this one would never show though)** 

NoMatch

**Comment by alexander-myltsev** [comment]
fixed by 58f99015e0595f1e802a110a531774dfc92f57c6 and https://github.com/GlobalNamesArchitecture/gnindex-front/commit/8ab4b8487af0388ee5ac2180de77a985dd28bdd6
