### ISSUE TITLE
As an API user I want to know how many databases carry matches to my name-string

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnindex#73]
One of quality assesments we use is number of databases where we found  a match for a name-string.
It should be found for every name-string, and located on the same level as 'total', 'suppliedInput', 'suppliedId', for example:

matchedDataSources: 36

in this example matchedDataSources will always be 36 when we search full database (independant on bestMatchOnly true or false). It returns number of data_sources we found a name in. 

In case where user specifically asked for dataSourceIds [1,2] it returns only number that was found in the subset of datasources. In the example it wold not exceed 2.

**Comment by alexander-myltsev** [comment]
closed by https://github.com/GlobalNamesArchitecture/gnindex/commit/0bd9b1a135a8042d030dfd702b05a4819b527132 and https://github.com/GlobalNamesArchitecture/gnindex/commit/1a2fc0eae93d688cc38b836fa1671fc17c23b45b
