### ISSUE TITLE
Fix `dataSources` and `preferredDatasources` interplay

### ISSUE THREAD

**Issue by alexander-myltsev** [GlobalNamesArchitecture/gnindex#77]
Cases:
- preferredDatasources is empty, datasources is empty: search over all available datasources, preferredDatasources is empty is results
- preferredDatasources is not empty, datasources is empty: search over all available datasources, results for preferredDatasources are filled according to provided datasources
- preferredDatasources is empty, datasources is not empty: search over provided available datasources, results for preferredDatasources are empty
- preferredDatasources is not empty, datasources is not empty: search over ~~provided available datasources (without extending the list of IDs by preferredDatasources)~~ the union of datasources and preferred datasources, results for preferredDatasources are filled according to provided datasources, results for datasources are filled accoriding to provided datasources.

`preferredDatasources` should not necessarily be a subset of `dataSources`.

**Comment by dimus** [comment]
The relationship of dataSources, preferredDataSources, total and matchedDataSources

1. preferredDatasources is empty, datasources is empty: **total** is the number of all found records, **matchedDataSources** is the number of unique dataSources that had a match

2. preferredDatasources is not empty, datasources is empty: **total** and **matchedDataSources** are the same as in case 1.

3. preferredDatasources is empty, datasources is not empty: **total** is the number of all found records in given subset of datasources. **matchedDataSources** is a number of a subset of given datasources that do have a match.

4. preferredDatasources is not empty, datasources is not empty: ??

**Comment by dimus** [comment]
When ``bestMatchOnly: true`` total: 1, matchedDataSources is not affected by bestMatchOnly
