### ISSUE TITLE
As a User I want api output fields to be congruent with output of resolver.globalnames.org

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnindex#8]
We need all output fields to cover semantically the fields in resolver.globalnames.org

**Comment by alexander-myltsev** [comment]
`currentName`

**Comment by alexander-myltsev** [comment]
Based on https://github.com/dimus/gni/wiki/api and http://resolver.globalnames.org/api rest fields are as follows:
- `preferred_data_sources`. Implicitly it should be a subset of data_source_ids: for any id in `preferred_data_sources` not in data_source_ids, add it in search.
- `with_context`. Description in source: models/names_resolver
- `with_canonical_ranks`
